/**
 * Match Routes
 * Handles resume-job matching requests
 */
const express = require('express');
const router = express.Router();
const { getActiveResume } = require('../repositories/resumeRepository');
const { createAnalysisSession } = require('../repositories/analysisRepository');
const { summarizeText } = require('../utils/textAnalytics');
const { performance } = require('perf_hooks');
const {
  calculateSimilarity,
  extractSkills,
  analyzeSkillGap,
  generateSuggestions,
} = require('../services/aiService');

const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

const computeCalibratedAtsScore = (similarityScore, gapData) => {
  const missingSkills = Array.isArray(gapData?.missingSkills) ? gapData.missingSkills : [];
  const matchedSkills = Array.isArray(gapData?.matchedSkills) ? gapData.matchedSkills : [];
  const totalSkills = missingSkills.length + matchedSkills.length;

  const semanticPercent = clamp((Number(similarityScore) || 0) * 100, 0, 100);
  const coveragePercent = totalSkills > 0
    ? (matchedSkills.length / totalSkills) * 100
    : semanticPercent;

  // Blend semantic match with explicit skill coverage.
  const blendedBase = 0.55 * semanticPercent + 0.45 * coveragePercent;

  // Weighted penalty based on skill importance generated by gap analysis.
  const totalImportance = [...missingSkills, ...matchedSkills]
    .reduce((sum, skill) => sum + (Number(skill?.importance) || 0.5), 0);
  const missingImportance = missingSkills
    .reduce((sum, skill) => sum + (Number(skill?.importance) || 0.5), 0);
  const weightedPenalty = totalImportance > 0
    ? (missingImportance / totalImportance) * 30
    : 0;

  // Extra penalty for critical missing skills.
  const criticalMissingCount = missingSkills
    .filter((skill) => (Number(skill?.importance) || 0) >= 0.75)
    .length;
  const criticalPenalty = Math.min(20, criticalMissingCount * 4);

  const atsScore = clamp(blendedBase - weightedPenalty - criticalPenalty, 5, 98);

  return {
    atsScore: Number(atsScore.toFixed(1)),
    scoreBreakdown: {
      semanticPercent: Number(semanticPercent.toFixed(1)),
      coveragePercent: Number(coveragePercent.toFixed(1)),
      blendedBase: Number(blendedBase.toFixed(1)),
      weightedPenalty: Number(weightedPenalty.toFixed(1)),
      criticalPenalty,
      criticalMissingCount,
    },
  };
};

/**
 * POST /api/match
 * Match resume with job description
 */
router.post('/', async (req, res) => {
  try {
    const processStart = performance.now();
    const { jobTitle, companyName, jobDescription } = req.body;
    
    // Validate required fields
    if (!jobDescription) {
      return res.status(400).json({
        success: false,
        error: 'Job description is required',
        code: 'MISSING_FIELDS'
      });
    }
    
    // Get resume text
    const resume = await getActiveResume();
    
    if (!resume) {
      return res.status(404).json({
        success: false,
        error: 'Resume not found. Please upload a resume first.',
        code: 'RESUME_NOT_FOUND'
      });
    }
    
    const stages = [];

    // Extract skills from resume and job
    const skillsStart = performance.now();
    const [resumeSkillsData, jobSkillsData] = await Promise.all([
      extractSkills(resume.resumeText),
      extractSkills(jobDescription),
    ]);
    stages.push({
      name: 'skills_extraction',
      durationMs: Number((performance.now() - skillsStart).toFixed(1)),
      outputSummary: {
        resumeSkillCount: (resumeSkillsData.skills || []).length,
        jobSkillCount: (jobSkillsData.skills || []).length,
      },
    });
    
    const resumeSkills = resumeSkillsData.skills || [];
    const jobSkills = jobSkillsData.skills || [];
    
    // Calculate similarity score
    const similarityStart = performance.now();
    const similarityData = await calculateSimilarity(
      resume.resumeText,
      jobDescription
    );
    stages.push({
      name: 'similarity',
      durationMs: Number((performance.now() - similarityStart).toFixed(1)),
      outputSummary: {
        similarityScore: similarityData.similarityScore || 0,
        semanticScorePercent: Number(((similarityData.similarityScore || 0) * 100).toFixed(1)),
      },
    });
    
    // Analyze skill gap
    const gapStart = performance.now();
    const gapData = await analyzeSkillGap(resumeSkills, jobSkills);
    stages.push({
      name: 'skill_gap',
      durationMs: Number((performance.now() - gapStart).toFixed(1)),
      outputSummary: {
        missingSkillsCount: (gapData.missingSkills || []).length,
        matchedSkillsCount: (gapData.matchedSkills || []).length,
        gapScore: gapData.gapScore || 0,
      },
    });
    
    const calibratedScore = computeCalibratedAtsScore(
      similarityData.similarityScore || 0,
      gapData
    );
    stages.push({
      name: 'ats_calibration',
      durationMs: 0,
      outputSummary: calibratedScore.scoreBreakdown,
    });

    // Generate suggestions
    const suggestionsStart = performance.now();
    const suggestionsData = await generateSuggestions(
      resume.resumeText,
      jobDescription,
      gapData.missingSkills?.map(s => s.skill) || []
    );
    stages.push({
      name: 'suggestions',
      durationMs: Number((performance.now() - suggestionsStart).toFixed(1)),
      outputSummary: {
        keywordSuggestionsCount: (suggestionsData.keywordSuggestions || []).length,
        bulletSuggestionsCount: (suggestionsData.bulletSuggestions || []).length,
        projectIdeasCount: (suggestionsData.projectIdeas || []).length,
      },
    });

    const totalDurationMs = Number((performance.now() - processStart).toFixed(1));
    
    // Build response
    const responsePayload = {
      success: true,
      match: {
        atsScore: calibratedScore.atsScore,
        similarityScore: similarityData.similarityScore || 0,
        missingSkills: gapData.missingSkills || [],
        matchedSkills: gapData.matchedSkills || [],
        scoreBreakdown: calibratedScore.scoreBreakdown,
        suggestions: {
          keywordSuggestions: suggestionsData.keywordSuggestions || [],
          bulletSuggestions: suggestionsData.bulletSuggestions || [],
          techAlignmentTips: suggestionsData.techAlignmentTips || [],
        },
        projectIdeas: suggestionsData.projectIdeas || [],
      },
    };

    // Save analysis telemetry for dashboard
    try {
      await createAnalysisSession({
        jobTitle: jobTitle || '',
        companyName: companyName || '',
        jobDescriptionPreview: summarizeText(jobDescription, 90),
        totalDurationMs,
        stages,
        resultSnapshot: responsePayload.match,
      });
    } catch (sessionError) {
      console.error('Failed to persist analysis session:', sessionError.message);
    }

    responsePayload.analysisMeta = {
      totalDurationMs,
      stageCount: stages.length,
    };

    res.json(responsePayload);
    
  } catch (error) {
    console.error('Match error:', error);
    res.status(500).json({
      success: false,
      error: error.message || 'Failed to match resume',
      code: error.code || 'MATCH_ERROR'
    });
  }
});

module.exports = router;
